module.exports = {
  warn: function () {},

  fixPeople: require('./fixers/people').fixPeople,
  fixBinField: require('./fixers/bin').fixBinField,
  fixBugsField: require('./fixers/bugs').fixBugsField,
  fixDependencies: require('./fixers/dependencies').fixDependencies,
  fixFilesField: require('./fixers/files').fixFilesField,
  fixHomepageField: require('./fixers/homepage').fixHomepageField,
  fixKeywordsField: require('./fixers/keywords').fixKeywordsField,
  fixLicenseField: require('./fixers/license').fixLicenseField,
  fixManField: require('./fixers/man').fixManField,
  fixModulesField: require('./fixers/modules').fixModulesField,
  fixNameField: require('./fixers/name').fixNameField,
  fixReadmeField: require('./fixers/readme').fixReadmeField,
  fixRepositoryField: require('./fixers/repository').fixRepositoryField,
  fixScriptsField: require('./fixers/scripts').fixScriptsField,
  fixTypos: require('./fixers/typos').fixTypos,
  fixVersionField: require('./fixers/version').fixVersionField,
  fixDescriptionField: require('./fixers/description').fixDescriptionField,
  fixBundleDependenciesField: require('./fixers/dependencies').fixBundleDependenciesField,
}
